# render.yaml
services:
  - type: web
    name: django-chat-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 --port 10000 whatsapp_clone.asgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: whatsapp_clone.settings
      - key: SECRET_KEY
        value: "<your-secret-key>"
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: your-postgres
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: your-redis
          property: connectionString
